---
abstract: 'Handles arrays of scalars or objects using integer ranges'
author:
  - 'Dominique Dumont'
build_requires:
  Data::Dumper: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Array-IntSpan
requires:
  Carp: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Array-IntSpan
  homepage: https://github.com/dod38fr/array-intspan-perl
  repository: https://github.com/dod38fr/array-intspan-perl.git
version: '2.003'
